// UI texts of the Sky view (tab "skyview") in Dutch, English and Greek. Keys 'sv.*' plus the tab names. Plain objects so tests can check them.
export const nl: Record<string, string> = {
  'tab.skyview': 'Planetarium', 'more.skyview': 'Kijk vanaf elke plek op aarde naar de sterrenhemel',
  'sv.intro': 'Kies een plek op aarde en kijk omhoog: sterren, sterrenbeelden, planeten, Maan, Zon, de Melkweg en satellieten, precies zoals ze er nu (of op elk ander moment) uitzien. Sleep om rond te kijken, knijp of scrol om te zoomen, tik op iets om het te herkennen.',
  'sv.place': 'Plaats', 'sv.placeSearch': 'Zoek een plaats of typ coördinaten…', 'sv.gps': 'Mijn locatie', 'sv.map': 'Kaart', 'sv.noPlace': 'Geen plaats gevonden. Probeer een andere spelling, of kies op de kaart.',
  'sv.useCoords': 'Ga naar {c}', 'sv.map.aria': 'Wereldkaart: tik om een plek te kiezen', 'sv.map.h': 'Tik om een plek te kiezen. Sleep om te verschuiven, knijp of scrol om te zoomen.',
  'sv.solarTime': 'zonnetijd', 'sv.solarTime.h': 'Lokale zonnetijd: de zon staat rond 12:00 op haar hoogst (zonder tijdzone of zomertijd)',
  'sv.time': 'Tijd', 'sv.timeH': 'De hemel volgt de klok van de app. Snelheid en pauze staan onderaan het scherm.',
  'sv.find': 'Zoek een object', 'sv.findPh': 'Sirius, Orion, Jupiter, M31, ISS…',
  'sv.filters': 'Wat toon je', 'sv.g.stars': 'Sterren en sterrenbeelden', 'sv.g.solar': 'Zonnestelsel', 'sv.g.sats': 'Satellieten', 'sv.g.deep': 'Diepe ruimte', 'sv.g.help': 'Hulplijnen en omgeving',
  'sv.l.stars': 'Sterren', 'sv.l.starNames': 'Sterrennamen', 'sv.l.lines': 'Figuurlijnen', 'sv.l.conNames': 'Namen sterrenbeelden', 'sv.l.sun': 'Zon', 'sv.l.moon': 'Maan', 'sv.l.planets': 'Planeten',
  'sv.l.sats': 'Satellieten (ISS e.a.)', 'sv.l.satsSunlitOnly': 'Alleen in zonlicht', 'sv.l.mw': 'Melkweg', 'sv.l.dso': 'Messier en deep-sky', 'sv.l.gridAz': 'Raster hoogte/richting', 'sv.l.gridEq': 'Raster equatoriaal',
  'sv.l.ecliptic': 'Ecliptica', 'sv.l.ground': 'Horizon en grond', 'sv.l.cardinals': 'Windstreken', 'sv.l.atmosphere': 'Dagkleur en schemering',
  'sv.magLim': 'Zwakste ster', 'sv.stars': 'sterren', 'sv.reset': 'Standaardinstellingen',
  'sv.sats.loading': 'Satellietgegevens laden…', 'sv.sats.ok': '{n} helderste satellieten en ruimtestations (CelesTrak, live berekend).', 'sv.sats.none': 'Geen satellietgegevens. Ze worden eenmalig met internet opgehaald en daarna bewaard.',
  'sv.arTitle': 'AR: richt je telefoon', 'sv.ar': 'AR', 'sv.ar.on': 'AR aan', 'sv.ar.h': 'Houd je telefoon omhoog: het scherm toont de hemel in de richting waarop je mikt (bewegingssensoren, geen camera). Sleep zijwaarts om de richting bij te stellen, knijp om te zoomen.',
  'sv.ar.calib': 'Beweeg je telefoon een paar keer in een 8-figuur om het kompas te kalibreren. Sleep zijwaarts om de richting bij te stellen.', 'sv.ar.rel': 'Dit toestel geeft geen kompasrichting door: het noorden klopt waarschijnlijk niet. Sleep zijwaarts om bij te stellen.',
  'sv.ar.none': 'Geen bewegingssensor gevonden. Sleep om rond te kijken.', 'sv.ar.denied': 'Geen toestemming voor de bewegingssensoren. Sta dit toe in de instellingen van je telefoon of browser.',
  'sv.zoomIn': 'Inzoomen', 'sv.zoomOut': 'Uitzoomen', 'sv.canvas': 'Sterrenhemel. Pijltjestoetsen draaien, plus en min zoomen.', 'sv.loading': 'Sterrenhemel laden…', 'sv.close': 'Sluiten',
  'sv.k.star': 'Ster', 'sv.k.sun': 'Zon', 'sv.k.moon': 'Maan', 'sv.k.planet': 'Planeet', 'sv.k.body': 'Zonnestelsel', 'sv.k.con': 'Sterrenbeeld', 'sv.k.dso': 'Deep-sky', 'sv.k.sat': 'Satelliet',
  'sv.type.galaxy': 'sterrenstelsel', 'sv.type.cluster': 'open sterrenhoop', 'sv.type.globular': 'bolhoop', 'sv.type.planetary': 'planetaire nevel', 'sv.type.nebula': 'nevel', 'sv.type.snr': 'supernovarest',
  'sv.col.0': 'blauwwit', 'sv.col.1': 'wit', 'sv.col.2': 'geelwit', 'sv.col.3': 'oranje', 'sv.col.4': 'rood',
  'sv.ly': 'lichtjaar', 'sv.lightMin': 'lichtminuten', 'sv.colour': 'Kleur', 'sv.transit': 'Hoogste punt', 'sv.alwaysUp': 'Gaat de komende 24 uur niet onder.', 'sv.alwaysDown': 'Komt de komende 24 uur niet boven de horizon.',
  'sv.solarNote': 'Tijden in lokale zonnetijd van de plek, voor de komende 24 uur.', 'sv.height': 'Hoogte boven de Aarde', 'sv.range': 'Afstand', 'sv.speed': 'Snelheid', 'sv.light': 'Zonlicht', 'sv.sunlit': 'in zonlicht', 'sv.shadow': 'in de schaduw van de Aarde',
  'sv.satVisible': 'Nu met het blote oog te zien: de satelliet vangt zonlicht terwijl het bij jou donker is.', 'sv.satNotVisible': 'Nu niet te zien: te licht, in de schaduw van de Aarde of te laag.',
  'sv.credits': 'Bronnen: sterren, sterrenbeelden, Messier-objecten en Melkweg uit d3-celestial van Olaf Frohn (BSD-3-Clause; Hipparcos, Messier/NGC, Milky Way outlines). Plaatsnamen: GeoNames via all-the-cities (CC BY 4.0 / MIT). Kustlijnen: Natural Earth (publiek domein). Satellieten: CelesTrak. Zon, Maan en planeten worden op je toestel berekend; zonder refractie en zonder nutatie van de sterren (< 0,3°).',
}
export const en: Record<string, string> = {
  'tab.skyview': 'Planetarium', 'more.skyview': 'Look at the night sky from anywhere on Earth',
  'sv.intro': 'Pick a place on Earth and look up: stars, constellations, planets, Moon, Sun, the Milky Way and satellites, exactly as they look now (or at any other moment). Drag to look around, pinch or scroll to zoom, tap anything to identify it.',
  'sv.place': 'Place', 'sv.placeSearch': 'Search a place or type coordinates…', 'sv.gps': 'My location', 'sv.map': 'Map', 'sv.noPlace': 'No place found. Try another spelling, or pick on the map.',
  'sv.useCoords': 'Go to {c}', 'sv.map.aria': 'World map: tap to choose a place', 'sv.map.h': 'Tap to choose a place. Drag to pan, pinch or scroll to zoom.',
  'sv.solarTime': 'solar time', 'sv.solarTime.h': 'Local solar time: the Sun is highest around 12:00 (no time zone or daylight saving)',
  'sv.time': 'Time', 'sv.timeH': 'The sky follows the app clock. Speed and pause are at the bottom of the screen.',
  'sv.find': 'Find an object', 'sv.findPh': 'Sirius, Orion, Jupiter, M31, ISS…',
  'sv.filters': 'What to show', 'sv.g.stars': 'Stars and constellations', 'sv.g.solar': 'Solar system', 'sv.g.sats': 'Satellites', 'sv.g.deep': 'Deep space', 'sv.g.help': 'Guides and surroundings',
  'sv.l.stars': 'Stars', 'sv.l.starNames': 'Star names', 'sv.l.lines': 'Constellation lines', 'sv.l.conNames': 'Constellation names', 'sv.l.sun': 'Sun', 'sv.l.moon': 'Moon', 'sv.l.planets': 'Planets',
  'sv.l.sats': 'Satellites (ISS etc.)', 'sv.l.satsSunlitOnly': 'Sunlit only', 'sv.l.mw': 'Milky Way', 'sv.l.dso': 'Messier and deep sky', 'sv.l.gridAz': 'Altitude/azimuth grid', 'sv.l.gridEq': 'Equatorial grid',
  'sv.l.ecliptic': 'Ecliptic', 'sv.l.ground': 'Horizon and ground', 'sv.l.cardinals': 'Compass points', 'sv.l.atmosphere': 'Daylight and twilight',
  'sv.magLim': 'Faintest star', 'sv.stars': 'stars', 'sv.reset': 'Reset to defaults',
  'sv.sats.loading': 'Loading satellite data…', 'sv.sats.ok': '{n} brightest satellites and space stations (CelesTrak, computed live).', 'sv.sats.none': 'No satellite data. It is fetched once with internet and kept afterwards.',
  'sv.arTitle': 'AR: point your phone', 'sv.ar': 'AR', 'sv.ar.on': 'AR on', 'sv.ar.h': 'Hold your phone up: the screen shows the sky in the direction you aim (motion sensors, no camera). Drag sideways to fine-tune the heading, pinch to zoom.',
  'sv.ar.calib': 'Move your phone in a figure of eight a few times to calibrate the compass. Drag sideways to fine-tune the heading.', 'sv.ar.rel': 'This device gives no compass heading: north is probably off. Drag sideways to correct it.',
  'sv.ar.none': 'No motion sensor found. Drag to look around.', 'sv.ar.denied': 'No permission for the motion sensors. Allow it in your phone or browser settings.',
  'sv.zoomIn': 'Zoom in', 'sv.zoomOut': 'Zoom out', 'sv.canvas': 'Night sky. Arrow keys turn, plus and minus zoom.', 'sv.loading': 'Loading the sky…', 'sv.close': 'Close',
  'sv.k.star': 'Star', 'sv.k.sun': 'Sun', 'sv.k.moon': 'Moon', 'sv.k.planet': 'Planet', 'sv.k.body': 'Solar system', 'sv.k.con': 'Constellation', 'sv.k.dso': 'Deep sky', 'sv.k.sat': 'Satellite',
  'sv.type.galaxy': 'galaxy', 'sv.type.cluster': 'open cluster', 'sv.type.globular': 'globular cluster', 'sv.type.planetary': 'planetary nebula', 'sv.type.nebula': 'nebula', 'sv.type.snr': 'supernova remnant',
  'sv.col.0': 'blue-white', 'sv.col.1': 'white', 'sv.col.2': 'yellow-white', 'sv.col.3': 'orange', 'sv.col.4': 'red',
  'sv.ly': 'light-years', 'sv.lightMin': 'light-minutes', 'sv.colour': 'Colour', 'sv.transit': 'Highest point', 'sv.alwaysUp': 'Does not set in the next 24 hours.', 'sv.alwaysDown': 'Does not rise above the horizon in the next 24 hours.',
  'sv.solarNote': 'Times in the place\'s local solar time, for the next 24 hours.', 'sv.height': 'Height above Earth', 'sv.range': 'Distance', 'sv.speed': 'Speed', 'sv.light': 'Sunlight', 'sv.sunlit': 'in sunlight', 'sv.shadow': 'in Earth\'s shadow',
  'sv.satVisible': 'Visible to the naked eye now: the satellite catches sunlight while it is dark where you are.', 'sv.satNotVisible': 'Not visible now: too bright a sky, in Earth\'s shadow or too low.',
  'sv.credits': 'Sources: stars, constellations, Messier objects and Milky Way from d3-celestial by Olaf Frohn (BSD-3-Clause; Hipparcos, Messier/NGC, Milky Way outlines). Place names: GeoNames via all-the-cities (CC BY 4.0 / MIT). Coastlines: Natural Earth (public domain). Satellites: CelesTrak. Sun, Moon and planets are computed on your device; no refraction and no nutation of the stars (< 0.3°).',
}
export const el: Record<string, string> = {
  'tab.skyview': 'Πλανητάριο', 'more.skyview': 'Δες τον ουρανό από οποιοδήποτε σημείο της Γης',
  'sv.intro': 'Διάλεξε ένα σημείο της Γης και κοίτα ψηλά: αστέρια, αστερισμούς, πλανήτες, Σελήνη, Ήλιο, τον Γαλαξία και δορυφόρους, όπως φαίνονται τώρα (ή οποιαδήποτε άλλη στιγμή). Σύρε για να κοιτάξεις γύρω, τσίμπημα ή κύλιση για ζουμ, πάτησε κάτι για να το αναγνωρίσεις.',
  'sv.place': 'Τοποθεσία', 'sv.placeSearch': 'Αναζήτηση τοποθεσίας ή συντεταγμένες…', 'sv.gps': 'Η θέση μου', 'sv.map': 'Χάρτης', 'sv.noPlace': 'Δεν βρέθηκε τοποθεσία. Δοκίμασε άλλη γραφή ή διάλεξε στον χάρτη.',
  'sv.useCoords': 'Μετάβαση σε {c}', 'sv.map.aria': 'Παγκόσμιος χάρτης: πάτησε για να διαλέξεις τοποθεσία', 'sv.map.h': 'Πάτησε για να διαλέξεις τοποθεσία. Σύρε για μετακίνηση, τσίμπημα ή κύλιση για ζουμ.',
  'sv.solarTime': 'ηλιακή ώρα', 'sv.solarTime.h': 'Τοπική ηλιακή ώρα: ο Ήλιος είναι ψηλότερα γύρω στις 12:00 (χωρίς ζώνη ώρας ή θερινή ώρα)',
  'sv.time': 'Ώρα', 'sv.timeH': 'Ο ουρανός ακολουθεί το ρολόι της εφαρμογής. Ταχύτητα και παύση βρίσκονται κάτω στην οθόνη.',
  'sv.find': 'Βρες ένα αντικείμενο', 'sv.findPh': 'Σείριος, Ωρίων, Δίας, M31, ISS…',
  'sv.filters': 'Τι εμφανίζεται', 'sv.g.stars': 'Αστέρια και αστερισμοί', 'sv.g.solar': 'Ηλιακό σύστημα', 'sv.g.sats': 'Δορυφόροι', 'sv.g.deep': 'Βαθύ διάστημα', 'sv.g.help': 'Βοηθητικές γραμμές και περιβάλλον',
  'sv.l.stars': 'Αστέρια', 'sv.l.starNames': 'Ονόματα αστεριών', 'sv.l.lines': 'Γραμμές αστερισμών', 'sv.l.conNames': 'Ονόματα αστερισμών', 'sv.l.sun': 'Ήλιος', 'sv.l.moon': 'Σελήνη', 'sv.l.planets': 'Πλανήτες',
  'sv.l.sats': 'Δορυφόροι (ISS κ.ά.)', 'sv.l.satsSunlitOnly': 'Μόνο φωτισμένοι', 'sv.l.mw': 'Γαλαξίας', 'sv.l.dso': 'Messier και βαθύ διάστημα', 'sv.l.gridAz': 'Πλέγμα ύψους/αζιμουθίου', 'sv.l.gridEq': 'Ισημερινό πλέγμα',
  'sv.l.ecliptic': 'Εκλειπτική', 'sv.l.ground': 'Ορίζοντας και έδαφος', 'sv.l.cardinals': 'Σημεία του ορίζοντα', 'sv.l.atmosphere': 'Φως ημέρας και λυκόφως',
  'sv.magLim': 'Αμυδρότερο αστέρι', 'sv.stars': 'αστέρια', 'sv.reset': 'Προεπιλογές',
  'sv.sats.loading': 'Φόρτωση δεδομένων δορυφόρων…', 'sv.sats.ok': '{n} φωτεινότεροι δορυφόροι και διαστημικοί σταθμοί (CelesTrak, ζωντανός υπολογισμός).', 'sv.sats.none': 'Δεν υπάρχουν δεδομένα δορυφόρων. Λαμβάνονται μία φορά με internet και αποθηκεύονται.',
  'sv.arTitle': 'AR: στόχευσε με το κινητό', 'sv.ar': 'AR', 'sv.ar.on': 'AR ενεργό', 'sv.ar.h': 'Κράτα το κινητό ψηλά: η οθόνη δείχνει τον ουρανό προς την κατεύθυνση που στοχεύεις (αισθητήρες κίνησης, χωρίς κάμερα). Σύρε πλάγια για να διορθώσεις τον προσανατολισμό, τσίμπημα για ζουμ.',
  'sv.ar.calib': 'Κούνησε το κινητό σε σχήμα οκτώ μερικές φορές για να βαθμονομηθεί η πυξίδα. Σύρε πλάγια για να διορθώσεις τον προσανατολισμό.', 'sv.ar.rel': 'Η συσκευή δεν δίνει κατεύθυνση πυξίδας: ο βορράς μάλλον δεν είναι σωστός. Σύρε πλάγια για διόρθωση.',
  'sv.ar.none': 'Δεν βρέθηκε αισθητήρας κίνησης. Σύρε για να κοιτάξεις γύρω.', 'sv.ar.denied': 'Δεν δόθηκε άδεια για τους αισθητήρες κίνησης. Επίτρεψέ το στις ρυθμίσεις του κινητού ή του προγράμματος περιήγησης.',
  'sv.zoomIn': 'Μεγέθυνση', 'sv.zoomOut': 'Σμίκρυνση', 'sv.canvas': 'Νυχτερινός ουρανός. Τα βέλη γυρίζουν, το plus και το minus κάνουν ζουμ.', 'sv.loading': 'Φόρτωση ουρανού…', 'sv.close': 'Κλείσιμο',
  'sv.k.star': 'Αστέρι', 'sv.k.sun': 'Ήλιος', 'sv.k.moon': 'Σελήνη', 'sv.k.planet': 'Πλανήτης', 'sv.k.body': 'Ηλιακό σύστημα', 'sv.k.con': 'Αστερισμός', 'sv.k.dso': 'Βαθύ διάστημα', 'sv.k.sat': 'Δορυφόρος',
  'sv.type.galaxy': 'γαλαξίας', 'sv.type.cluster': 'ανοιχτό σμήνος', 'sv.type.globular': 'σφαιρωτό σμήνος', 'sv.type.planetary': 'πλανητικό νεφέλωμα', 'sv.type.nebula': 'νεφέλωμα', 'sv.type.snr': 'υπόλειμμα υπερκαινοφανούς',
  'sv.col.0': 'μπλε-λευκό', 'sv.col.1': 'λευκό', 'sv.col.2': 'κιτρινόλευκο', 'sv.col.3': 'πορτοκαλί', 'sv.col.4': 'κόκκινο',
  'sv.ly': 'έτη φωτός', 'sv.lightMin': 'λεπτά φωτός', 'sv.colour': 'Χρώμα', 'sv.transit': 'Ψηλότερο σημείο', 'sv.alwaysUp': 'Δεν δύει τις επόμενες 24 ώρες.', 'sv.alwaysDown': 'Δεν ανατέλλει τις επόμενες 24 ώρες.',
  'sv.solarNote': 'Ώρες σε τοπική ηλιακή ώρα του σημείου, για τις επόμενες 24 ώρες.', 'sv.height': 'Ύψος πάνω από τη Γη', 'sv.range': 'Απόσταση', 'sv.speed': 'Ταχύτητα', 'sv.light': 'Ηλιακό φως', 'sv.sunlit': 'στο φως του Ήλιου', 'sv.shadow': 'στη σκιά της Γης',
  'sv.satVisible': 'Φαίνεται τώρα με γυμνό μάτι: ο δορυφόρος πιάνει ηλιακό φως ενώ σκοτεινιάζει εκεί που βρίσκεσαι.', 'sv.satNotVisible': 'Δεν φαίνεται τώρα: ο ουρανός είναι φωτεινός, ο δορυφόρος στη σκιά της Γης ή πολύ χαμηλά.',
  'sv.credits': 'Πηγές: αστέρια, αστερισμοί, αντικείμενα Messier και Γαλαξίας από το d3-celestial του Olaf Frohn (BSD-3-Clause· Hipparcos, Messier/NGC). Ονόματα τοποθεσιών: GeoNames μέσω all-the-cities (CC BY 4.0 / MIT). Ακτογραμμές: Natural Earth (κοινό κτήμα). Δορυφόροι: CelesTrak. Ήλιος, Σελήνη και πλανήτες υπολογίζονται στη συσκευή σου· χωρίς διάθλαση και χωρίς κλόνιση των αστεριών (< 0,3°).',
}
