// Texts for notifications: `NOTIF` is sent to the native worker / desktop poller inside the config (keys fixed by contract v1) and used by the JS
// planner; `UI` are the settings-sheet strings (keys 'al.*').
export type L = 'nl' | 'en' | 'el'

export const NOTIF: Record<L, Record<string, string>> = {
  nl: {
    kp_title: 'Geomagnetische storm {g}', kp_body: 'Kp {kp} — noorderlicht mogelijk tot ~{lat}° breedte',
    aurora_title: 'Noorderlicht-kans {pct}%', aurora_body: '{pct}% kans op noorderlicht boven {place}',
    flare_title: 'Zonnevlam {cls}', flare_body: 'Röntgenpiek {cls} om {time}',
    cme_title: 'Zonne-uitbarsting (CME)', cme_body: '{msg}',
    radio_title: 'Radio-uitbarsting op de Zon', radio_body: '{msg}',
    watch_title: 'Stormwaarschuwing {g}', watch_body: '{msg}',
    launch_title: 'Lancering over {min} min', launch_body: '{name} — {provider}',
    channel_spaceweather: 'Ruimteweer', channel_launches: 'Lanceringen',
    iss_title: 'ISS zichtbaar over {min} min', iss_body: '{from} → {to}, hoogst {el}° om {time}',
    ev_body: '{when}', ev_tomorrow: 'Morgen', ev_today: 'Vandaag',
    sum_title: 'Vanavond te zien', sum_none: 'Geen planeten zichtbaar', sum_iss: 'ISS {time} ({el}°)',
    test_title: 'Test: meldingen werken', test_body: 'Zo ziet een melding van Periapsis eruit.',
    channel_sky: 'Hemel-agenda',
  },
  en: {
    kp_title: 'Geomagnetic storm {g}', kp_body: 'Kp {kp} — aurora possible down to ~{lat}° latitude',
    aurora_title: 'Aurora chance {pct}%', aurora_body: '{pct}% chance of aurora over {place}',
    flare_title: 'Solar flare {cls}', flare_body: 'X-ray peak {cls} at {time}',
    cme_title: 'Solar eruption (CME)', cme_body: '{msg}',
    radio_title: 'Solar radio burst', radio_body: '{msg}',
    watch_title: 'Storm watch {g}', watch_body: '{msg}',
    launch_title: 'Launch in {min} min', launch_body: '{name} — {provider}',
    channel_spaceweather: 'Space weather', channel_launches: 'Launches',
    iss_title: 'ISS visible in {min} min', iss_body: '{from} → {to}, up to {el}° at {time}',
    ev_body: '{when}', ev_tomorrow: 'Tomorrow', ev_today: 'Today',
    sum_title: 'Tonight in the sky', sum_none: 'No planets visible', sum_iss: 'ISS {time} ({el}°)',
    test_title: 'Test: notifications work', test_body: 'This is what a Periapsis notification looks like.',
    channel_sky: 'Sky calendar',
  },
  el: {
    kp_title: 'Γεωμαγνητική καταιγίδα {g}', kp_body: 'Kp {kp} — πιθανό σέλας έως ~{lat}° γεωγραφικό πλάτος',
    aurora_title: 'Πιθανότητα σέλαος {pct}%', aurora_body: '{pct}% πιθανότητα σέλαος πάνω από {place}',
    flare_title: 'Ηλιακή έκλαμψη {cls}', flare_body: 'Κορύφωση ακτίνων Χ {cls} στις {time}',
    cme_title: 'Ηλιακή έκρηξη (CME)', cme_body: '{msg}',
    radio_title: 'Ραδιοεκπομπή του Ήλιου', radio_body: '{msg}',
    watch_title: 'Προειδοποίηση καταιγίδας {g}', watch_body: '{msg}',
    launch_title: 'Εκτόξευση σε {min} λεπτά', launch_body: '{name} — {provider}',
    channel_spaceweather: 'Διαστημικός καιρός', channel_launches: 'Εκτοξεύσεις',
    iss_title: 'Το ISS φαίνεται σε {min} λεπτά', iss_body: '{from} → {to}, έως {el}° στις {time}',
    ev_body: '{when}', ev_tomorrow: 'Αύριο', ev_today: 'Σήμερα',
    sum_title: 'Απόψε στον ουρανό', sum_none: 'Κανένας πλανήτης ορατός', sum_iss: 'ISS {time} ({el}°)',
    test_title: 'Δοκιμή: οι ειδοποιήσεις λειτουργούν', test_body: 'Έτσι φαίνεται μια ειδοποίηση του Periapsis.',
    channel_sky: 'Ημερολόγιο ουρανού',
  },
}

export const UI: Record<L, Record<string, string>> = {
  nl: {
    'al.title': 'Meldingen', 'al.intro': 'Krijg een melding bij ruimteweer, hemelgebeurtenissen en lanceringen, ook als de app dicht is. Standaard staat alles uit.',
    'al.permission': 'Meldingen toestaan', 'al.perm.ok': 'Toestemming: aan', 'al.perm.no': 'Toestemming ontbreekt: tik op de knop hierboven', 'al.perm.web': 'Meldingen werken in de Android- en Windows-app. In de browser alleen terwijl deze open staat.',
    'al.test': 'Test melding', 'al.test.sent': 'Testmelding verstuurd', 'al.test.fail': 'Kon geen melding sturen',
    'al.lastRun': 'Laatste controle: {t}', 'al.never': 'nog niet', 'al.error': 'Fout: {e}', 'al.scheduled': '{n} meldingen ingepland', 'al.checkNow': 'Nu controleren',
    'al.sw': 'Ruimteweer', 'al.sw.h': 'Geomagnetische storm, noorderlicht, zonnevlammen.', 'al.sw.kp': 'Storm vanaf', 'al.sw.aurora': 'Noorderlicht bij mij', 'al.sw.auroraMin': 'Minimale kans',
    'al.sw.flare': 'Zonnevlammen', 'al.flare.off': 'Uit', 'al.flare.M': 'M-klasse en sterker', 'al.flare.X': 'Alleen X-klasse',
    'al.sw.cme': 'CME en type II-uitbarsting', 'al.sw.radio': 'Radio-uitbarstingen', 'al.sw.watches': 'Stormwaarschuwingen (watch)',
    'al.sky': 'Hemel-agenda', 'al.sky.h': 'Berekend op jouw plek, voor de komende 10 dagen.', 'al.sky.iss': 'Zichtbare ISS-overkomsten', 'al.sky.meteor': 'Meteorenzwermen (piek)', 'al.sky.eclipse': 'Verduisteringen',
    'al.sky.conj': 'Conjuncties en kleine afstanden', 'al.sky.moon': 'Volle en nieuwe maan', 'al.sky.opp': 'Planeten in oppositie',
    'al.la': 'Lanceringen', 'al.la.h': 'Raketlanceringen wereldwijd, kort voor de start.', 'al.la.lead': 'Hoe lang van tevoren',
    'al.min': '{n} min', 'al.sum': 'Dagelijkse samenvatting', 'al.sum.h': 'Wat je vanavond ziet: planeten, maan, ISS, gebeurtenissen.', 'al.sum.morning': 'Ochtend', 'al.sum.evening': 'Avond', 'al.sum.at': 'Tijd',
    'al.quiet': 'Stille uren', 'al.quiet.h': 'Geen meldingen in deze periode; wat je mist komt erna.', 'al.quiet.from': 'Van', 'al.quiet.to': 'Tot',
    'al.desk': 'Windows', 'al.desk.tray': 'Periapsis blijft draaien in het systeemvak zodat meldingen aankomen als je het venster sluit.', 'al.desk.login': 'Starten met Windows',
    'al.on': 'Aan', 'al.setup': 'Instelling',
  },
  en: {
    'al.title': 'Notifications', 'al.intro': 'Get notified about space weather, sky events and launches, even when the app is closed. Everything is off by default.',
    'al.permission': 'Allow notifications', 'al.perm.ok': 'Permission: granted', 'al.perm.no': 'Permission missing: tap the button above', 'al.perm.web': 'Notifications work in the Android and Windows apps. In a browser only while this page is open.',
    'al.test': 'Test notification', 'al.test.sent': 'Test notification sent', 'al.test.fail': 'Could not send a notification',
    'al.lastRun': 'Last check: {t}', 'al.never': 'not yet', 'al.error': 'Error: {e}', 'al.scheduled': '{n} notifications scheduled', 'al.checkNow': 'Check now',
    'al.sw': 'Space weather', 'al.sw.h': 'Geomagnetic storms, aurora, solar flares.', 'al.sw.kp': 'Storm from', 'al.sw.aurora': 'Aurora at my location', 'al.sw.auroraMin': 'Minimum chance',
    'al.sw.flare': 'Solar flares', 'al.flare.off': 'Off', 'al.flare.M': 'M-class and stronger', 'al.flare.X': 'X-class only',
    'al.sw.cme': 'CME and type II bursts', 'al.sw.radio': 'Radio bursts', 'al.sw.watches': 'Storm watches',
    'al.sky': 'Sky calendar', 'al.sky.h': 'Computed for your location, for the next 10 days.', 'al.sky.iss': 'Visible ISS passes', 'al.sky.meteor': 'Meteor shower peaks', 'al.sky.eclipse': 'Eclipses',
    'al.sky.conj': 'Conjunctions and close approaches', 'al.sky.moon': 'Full and new Moon', 'al.sky.opp': 'Planet oppositions',
    'al.la': 'Launches', 'al.la.h': 'Rocket launches worldwide, shortly before liftoff.', 'al.la.lead': 'Lead time',
    'al.min': '{n} min', 'al.sum': 'Daily summary', 'al.sum.h': 'What you can see tonight: planets, Moon, ISS, events.', 'al.sum.morning': 'Morning', 'al.sum.evening': 'Evening', 'al.sum.at': 'Time',
    'al.quiet': 'Quiet hours', 'al.quiet.h': 'No notifications in this period; what you miss arrives afterwards.', 'al.quiet.from': 'From', 'al.quiet.to': 'To',
    'al.desk': 'Windows', 'al.desk.tray': 'Periapsis keeps running in the system tray so notifications arrive when you close the window.', 'al.desk.login': 'Start with Windows',
    'al.on': 'On', 'al.setup': 'Setting',
  },
  el: {
    'al.title': 'Ειδοποιήσεις', 'al.intro': 'Λάβετε ειδοποίηση για διαστημικό καιρό, γεγονότα του ουρανού και εκτοξεύσεις, ακόμη και με κλειστή εφαρμογή. Όλα είναι απενεργοποιημένα από προεπιλογή.',
    'al.permission': 'Να επιτρέπονται οι ειδοποιήσεις', 'al.perm.ok': 'Άδεια: δόθηκε', 'al.perm.no': 'Λείπει η άδεια: πατήστε το κουμπί παραπάνω', 'al.perm.web': 'Οι ειδοποιήσεις λειτουργούν στις εφαρμογές Android και Windows. Στον περιηγητή μόνο όσο η σελίδα είναι ανοιχτή.',
    'al.test': 'Δοκιμαστική ειδοποίηση', 'al.test.sent': 'Στάλθηκε δοκιμαστική ειδοποίηση', 'al.test.fail': 'Αδυναμία αποστολής ειδοποίησης',
    'al.lastRun': 'Τελευταίος έλεγχος: {t}', 'al.never': 'δεν έγινε ακόμη', 'al.error': 'Σφάλμα: {e}', 'al.scheduled': '{n} προγραμματισμένες ειδοποιήσεις', 'al.checkNow': 'Έλεγχος τώρα',
    'al.sw': 'Διαστημικός καιρός', 'al.sw.h': 'Γεωμαγνητικές καταιγίδες, σέλας, ηλιακές εκλάμψεις.', 'al.sw.kp': 'Καταιγίδα από', 'al.sw.aurora': 'Σέλας στην τοποθεσία μου', 'al.sw.auroraMin': 'Ελάχιστη πιθανότητα',
    'al.sw.flare': 'Ηλιακές εκλάμψεις', 'al.flare.off': 'Ανενεργό', 'al.flare.M': 'Κλάση M και ισχυρότερες', 'al.flare.X': 'Μόνο κλάση X',
    'al.sw.cme': 'CME και εκρήξεις τύπου II', 'al.sw.radio': 'Ραδιοεκρήξεις', 'al.sw.watches': 'Προειδοποιήσεις καταιγίδας (watch)',
    'al.sky': 'Ημερολόγιο ουρανού', 'al.sky.h': 'Υπολογισμένο για την τοποθεσία σας, για τις επόμενες 10 ημέρες.', 'al.sky.iss': 'Ορατές διελεύσεις του ISS', 'al.sky.meteor': 'Κορυφώσεις διαττόντων', 'al.sky.eclipse': 'Εκλείψεις',
    'al.sky.conj': 'Συζεύξεις και κοντινές προσεγγίσεις', 'al.sky.moon': 'Πανσέληνος και Νέα Σελήνη', 'al.sky.opp': 'Αντιθέσεις πλανητών',
    'al.la': 'Εκτοξεύσεις', 'al.la.h': 'Εκτοξεύσεις πυραύλων παγκοσμίως, λίγο πριν την εκτόξευση.', 'al.la.lead': 'Προειδοποίηση πριν',
    'al.min': '{n} λεπτά', 'al.sum': 'Ημερήσια σύνοψη', 'al.sum.h': 'Τι βλέπετε απόψε: πλανήτες, Σελήνη, ISS, γεγονότα.', 'al.sum.morning': 'Πρωί', 'al.sum.evening': 'Βράδυ', 'al.sum.at': 'Ώρα',
    'al.quiet': 'Ώρες ησυχίας', 'al.quiet.h': 'Καμία ειδοποίηση σε αυτό το διάστημα· όσα χάσετε φτάνουν μετά.', 'al.quiet.from': 'Από', 'al.quiet.to': 'Έως',
    'al.desk': 'Windows', 'al.desk.tray': 'Το Periapsis συνεχίζει να τρέχει στην περιοχή ειδοποιήσεων ώστε να φτάνουν οι ειδοποιήσεις όταν κλείνετε το παράθυρο.', 'al.desk.login': 'Εκκίνηση με τα Windows',
    'al.on': 'Ενεργό', 'al.setup': 'Ρύθμιση',
  },
}
